In [0]:
import numpy as np

In [0]:
# Setup for questions 1 and 2
arr1=np.arange(40).reshape(8,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [0]:
# Q1. From arr1 you have to fetch out every alternate column starting from col1

import numpy as np

arr1=np.arange(40).reshape(8,5)
arr1
arr1[0:8, 1::2]

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18],
       [21, 23],
       [26, 28],
       [31, 33],
       [36, 38]])

In [0]:
# Q2. From arr1 fetch an array which would contain {0,2,4} {15,17,19} and {30,32,34} 

import numpy as np

arr1=np.arange(40).reshape(8,5)
arr1
arr1[::3, ::2]

array([[ 0,  2,  4],
       [15, 17, 19],
       [30, 32, 34]])

In [0]:
# Setup for question

# Generating a random numpy array of intergers ranging between 1 and 100

arr2=np.random.randint(low=1, high=10000, size=10).reshape(2,5)
arr2

array([[6749, 2326, 9506, 4980, 4126],
       [3833, 1653, 4874, 9166,  297]])

 **Normalization** rescales the values into a range of [0,1]. This might be useful in some cases where all parameters need to have the same positive scale. You have to do this a lot in machine learning for eg you are working with 2 cols, one is total runs scored by a batsman(in the scale of 1000s), and the second is number of matches played by him(in the scale of 10s). The formula for normalization is given below

 Xchanged=(X−Xmin)/(Xmax−Xmin)

In [0]:
# Q3. Write a code to normalize arr2.

import numpy as np

arr2=np.random.randint(low=1, high=10000, size=10).reshape(2,5)
max=arr2.max()
min=arr2.min()
array=(arr2-arr2.min())/(arr2.max()-arr2.min())
array

array([[0.49516635, 0.07394852, 0.29290647, 0.        , 0.64469554],
       [0.13358443, 0.81694915, 1.        , 0.72680477, 0.48022599]])

In [0]:
np.percentile(arr1,25)

9.75

Missing values are a pain in the a**(sorry for language). But yes trust me.

In [0]:
# Q4. How would you check if your numpy array has some missing values?
# Hint: Thoda research karo numpy me existing functions hai

#we would check it by passing the code of a boolean will raise an exception, and comparisons with it will produce numpy.NA instead of True or False and by checking that np.NA  singleton may accept a dtype=keyword parameter  indicating that it should be treated as an NA of a particular data type. 

#example

arr9=[1,2,np.nan,np.nan,50,87.0,100.0,np.nan]
np.isnan(arr9)





array([False, False,  True,  True, False, False, False,  True])

In [0]:
# Q5. Write a function which will accept 2 arguments.
# First: A 1D numpy array arr
# Second: An integer n {Please make sure n<=len(arr)}

# Output: The output should be the nth largest item out of the array

# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40

import numpy as np

def nthm(arr,n):
  
  arr2.sort()
  return arr[-n]
arr4=np.array([1,2,5,20,0,88])
nthm(arr4,3)

20